# fly.toml app configuration file generated for dramastorebot on 2024-01-13T06:11:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dramastorebot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "heroku/buildpacks:22"

[env]
  PORT = ""

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256